# main.py — Generated by VIA for: Build a hospital management system with doctor appointment booking, patient records management, prescription tracking, and billing. Use React frontend, FastAPI backend, PostgreSQL database. Clean medical blue theme, mobile-first design.
from fastapi import FastAPI, HTTPException, Depends
from fastapi.middleware.cors import CORSMiddleware
from database import engine, get_db
from models import Base, Appointment, Patient, Billing, Doctor, Book
from sqlalchemy.orm import Session
import os

app = FastAPI(
    title="Build A Hospital Management System With",
    description="Generated by VIA — Autonomous AI Digital Team",
    version="1.0.0"
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

@app.on_event("startup")
def on_startup():
    try:
        Base.metadata.create_all(bind=engine)
    except Exception as e:
        import logging as _log
        _log.getLogger("via").warning(f"DB init warning: {e}")


@app.get("/")
def root():
    return {"app": "Build A Hospital Management System With", "status": "running", "docs": "/docs"}

@app.get("/health")
def health():
    return {"status": "healthy"}


# ── APPOINTMENTS endpoints ──────────────────────────────────────────────
@app.get("/api/v1/appointments")
def get_appointments(skip: int = 0, limit: int = 100, db: Session = Depends(get_db)):
    items = db.query(Appointment).offset(skip).limit(limit).all()
    return {"appointments": [{"doctor_name": str(i.doctor_name) if hasattr(i, "doctor_name") else None, "department": str(i.department) if hasattr(i, "department") else None, "patient_name": str(i.patient_name) if hasattr(i, "patient_name") else None, "appointment_date": str(i.appointment_date) if hasattr(i, "appointment_date") else None, "status": str(i.status) if hasattr(i, "status") else None, "id": str(i.id) if hasattr(i, "id") else None, "created_at": str(i.created_at) if hasattr(i, "created_at") else None} for i in items],
            "total": db.query(Appointment).count()}

@app.get("/api/v1/appointments/{item_id}")
def get_appointment(item_id: int, db: Session = Depends(get_db)):
    item = db.query(Appointment).filter(Appointment.id == item_id).first()
    if not item:
        raise HTTPException(status_code=404, detail="Appointment not found")
    return {"doctor_name": str(i.doctor_name) if hasattr(i, "doctor_name") else None, "department": str(i.department) if hasattr(i, "department") else None, "patient_name": str(i.patient_name) if hasattr(i, "patient_name") else None, "appointment_date": str(i.appointment_date) if hasattr(i, "appointment_date") else None, "status": str(i.status) if hasattr(i, "status") else None, "id": str(i.id) if hasattr(i, "id") else None, "created_at": str(i.created_at) if hasattr(i, "created_at") else None}

@app.post("/api/v1/appointments")
def create_appointment(payload: dict, db: Session = Depends(get_db)):
    item = Appointment(
        doctor_name=payload.get("doctor_name", "")
        department=payload.get("department", "")
        patient_name=payload.get("patient_name", "")
        appointment_date=payload.get("appointment_date", "")
        status=payload.get("status", 'scheduled')
    )
    db.add(item); db.commit(); db.refresh(item)
    return {"doctor_name": str(i.doctor_name) if hasattr(i, "doctor_name") else None, "department": str(i.department) if hasattr(i, "department") else None, "patient_name": str(i.patient_name) if hasattr(i, "patient_name") else None, "appointment_date": str(i.appointment_date) if hasattr(i, "appointment_date") else None, "status": str(i.status) if hasattr(i, "status") else None, "id": str(i.id) if hasattr(i, "id") else None, "created_at": str(i.created_at) if hasattr(i, "created_at") else None}

@app.put("/api/v1/appointments/{item_id}")
def update_appointment(item_id: int, payload: dict, db: Session = Depends(get_db)):
    item = db.query(Appointment).filter(Appointment.id == item_id).first()
    if not item:
        raise HTTPException(status_code=404, detail="Appointment not found")
    for key, val in payload.items():
        if hasattr(item, key):
            setattr(item, key, val)
    db.commit(); db.refresh(item)
    return {"doctor_name": str(i.doctor_name) if hasattr(i, "doctor_name") else None, "department": str(i.department) if hasattr(i, "department") else None, "patient_name": str(i.patient_name) if hasattr(i, "patient_name") else None, "appointment_date": str(i.appointment_date) if hasattr(i, "appointment_date") else None, "status": str(i.status) if hasattr(i, "status") else None, "id": str(i.id) if hasattr(i, "id") else None, "created_at": str(i.created_at) if hasattr(i, "created_at") else None}

@app.delete("/api/v1/appointments/{item_id}")
def delete_appointment(item_id: int, db: Session = Depends(get_db)):
    item = db.query(Appointment).filter(Appointment.id == item_id).first()
    if not item:
        raise HTTPException(status_code=404, detail="Appointment not found")
    db.delete(item); db.commit()
    return {"deleted": item_id}

# Short alias routes for /appointments
@app.get("/appointments")
def alias_get_appointments(skip: int = 0, limit: int = 100, db: Session = Depends(get_db)):
    return get_appointments(skip=skip, limit=limit, db=db)

@app.post("/appointments")
def alias_create_appointments(payload: dict, db: Session = Depends(get_db)):
    return create_appointment(payload=payload, db=db)

# ── PATIENTS endpoints ──────────────────────────────────────────────
@app.get("/api/v1/patients")
def get_patients(skip: int = 0, limit: int = 100, db: Session = Depends(get_db)):
    items = db.query(Patient).offset(skip).limit(limit).all()
    return {"patients": [{"name": str(i.name) if hasattr(i, "name") else None, "age": str(i.age) if hasattr(i, "age") else None, "blood_group": str(i.blood_group) if hasattr(i, "blood_group") else None, "contact": str(i.contact) if hasattr(i, "contact") else None, "diagnosis": str(i.diagnosis) if hasattr(i, "diagnosis") else None, "status": str(i.status) if hasattr(i, "status") else None, "id": str(i.id) if hasattr(i, "id") else None, "created_at": str(i.created_at) if hasattr(i, "created_at") else None} for i in items],
            "total": db.query(Patient).count()}

@app.get("/api/v1/patients/{item_id}")
def get_patient(item_id: int, db: Session = Depends(get_db)):
    item = db.query(Patient).filter(Patient.id == item_id).first()
    if not item:
        raise HTTPException(status_code=404, detail="Patient not found")
    return {"name": str(i.name) if hasattr(i, "name") else None, "age": str(i.age) if hasattr(i, "age") else None, "blood_group": str(i.blood_group) if hasattr(i, "blood_group") else None, "contact": str(i.contact) if hasattr(i, "contact") else None, "diagnosis": str(i.diagnosis) if hasattr(i, "diagnosis") else None, "status": str(i.status) if hasattr(i, "status") else None, "id": str(i.id) if hasattr(i, "id") else None, "created_at": str(i.created_at) if hasattr(i, "created_at") else None}

@app.post("/api/v1/patients")
def create_patient(payload: dict, db: Session = Depends(get_db)):
    item = Patient(
        name=payload.get("name", "")
        age=payload.get("age", 0)
        blood_group=payload.get("blood_group", "")
        contact=payload.get("contact", "")
        diagnosis=payload.get("diagnosis", "")
        status=payload.get("status", 'active')
    )
    db.add(item); db.commit(); db.refresh(item)
    return {"name": str(i.name) if hasattr(i, "name") else None, "age": str(i.age) if hasattr(i, "age") else None, "blood_group": str(i.blood_group) if hasattr(i, "blood_group") else None, "contact": str(i.contact) if hasattr(i, "contact") else None, "diagnosis": str(i.diagnosis) if hasattr(i, "diagnosis") else None, "status": str(i.status) if hasattr(i, "status") else None, "id": str(i.id) if hasattr(i, "id") else None, "created_at": str(i.created_at) if hasattr(i, "created_at") else None}

@app.put("/api/v1/patients/{item_id}")
def update_patient(item_id: int, payload: dict, db: Session = Depends(get_db)):
    item = db.query(Patient).filter(Patient.id == item_id).first()
    if not item:
        raise HTTPException(status_code=404, detail="Patient not found")
    for key, val in payload.items():
        if hasattr(item, key):
            setattr(item, key, val)
    db.commit(); db.refresh(item)
    return {"name": str(i.name) if hasattr(i, "name") else None, "age": str(i.age) if hasattr(i, "age") else None, "blood_group": str(i.blood_group) if hasattr(i, "blood_group") else None, "contact": str(i.contact) if hasattr(i, "contact") else None, "diagnosis": str(i.diagnosis) if hasattr(i, "diagnosis") else None, "status": str(i.status) if hasattr(i, "status") else None, "id": str(i.id) if hasattr(i, "id") else None, "created_at": str(i.created_at) if hasattr(i, "created_at") else None}

@app.delete("/api/v1/patients/{item_id}")
def delete_patient(item_id: int, db: Session = Depends(get_db)):
    item = db.query(Patient).filter(Patient.id == item_id).first()
    if not item:
        raise HTTPException(status_code=404, detail="Patient not found")
    db.delete(item); db.commit()
    return {"deleted": item_id}

# Short alias routes for /patients
@app.get("/patients")
def alias_get_patients(skip: int = 0, limit: int = 100, db: Session = Depends(get_db)):
    return get_patients(skip=skip, limit=limit, db=db)

@app.post("/patients")
def alias_create_patients(payload: dict, db: Session = Depends(get_db)):
    return create_patient(payload=payload, db=db)

# ── BILLING endpoints ──────────────────────────────────────────────
@app.get("/api/v1/billing")
def get_billing(skip: int = 0, limit: int = 100, db: Session = Depends(get_db)):
    items = db.query(Billing).offset(skip).limit(limit).all()
    return {"billing": [{"patient_name": str(i.patient_name) if hasattr(i, "patient_name") else None, "amount": str(i.amount) if hasattr(i, "amount") else None, "status": str(i.status) if hasattr(i, "status") else None, "description": str(i.description) if hasattr(i, "description") else None, "id": str(i.id) if hasattr(i, "id") else None, "created_at": str(i.created_at) if hasattr(i, "created_at") else None} for i in items],
            "total": db.query(Billing).count()}

@app.get("/api/v1/billing/{item_id}")
def get_billing(item_id: int, db: Session = Depends(get_db)):
    item = db.query(Billing).filter(Billing.id == item_id).first()
    if not item:
        raise HTTPException(status_code=404, detail="Billing not found")
    return {"patient_name": str(i.patient_name) if hasattr(i, "patient_name") else None, "amount": str(i.amount) if hasattr(i, "amount") else None, "status": str(i.status) if hasattr(i, "status") else None, "description": str(i.description) if hasattr(i, "description") else None, "id": str(i.id) if hasattr(i, "id") else None, "created_at": str(i.created_at) if hasattr(i, "created_at") else None}

@app.post("/api/v1/billing")
def create_billing(payload: dict, db: Session = Depends(get_db)):
    item = Billing(
        patient_name=payload.get("patient_name", "")
        amount=payload.get("amount", 0.0)
        status=payload.get("status", 'pending')
        description=payload.get("description", "")
    )
    db.add(item); db.commit(); db.refresh(item)
    return {"patient_name": str(i.patient_name) if hasattr(i, "patient_name") else None, "amount": str(i.amount) if hasattr(i, "amount") else None, "status": str(i.status) if hasattr(i, "status") else None, "description": str(i.description) if hasattr(i, "description") else None, "id": str(i.id) if hasattr(i, "id") else None, "created_at": str(i.created_at) if hasattr(i, "created_at") else None}

@app.put("/api/v1/billing/{item_id}")
def update_billing(item_id: int, payload: dict, db: Session = Depends(get_db)):
    item = db.query(Billing).filter(Billing.id == item_id).first()
    if not item:
        raise HTTPException(status_code=404, detail="Billing not found")
    for key, val in payload.items():
        if hasattr(item, key):
            setattr(item, key, val)
    db.commit(); db.refresh(item)
    return {"patient_name": str(i.patient_name) if hasattr(i, "patient_name") else None, "amount": str(i.amount) if hasattr(i, "amount") else None, "status": str(i.status) if hasattr(i, "status") else None, "description": str(i.description) if hasattr(i, "description") else None, "id": str(i.id) if hasattr(i, "id") else None, "created_at": str(i.created_at) if hasattr(i, "created_at") else None}

@app.delete("/api/v1/billing/{item_id}")
def delete_billing(item_id: int, db: Session = Depends(get_db)):
    item = db.query(Billing).filter(Billing.id == item_id).first()
    if not item:
        raise HTTPException(status_code=404, detail="Billing not found")
    db.delete(item); db.commit()
    return {"deleted": item_id}

# Short alias routes for /billing
@app.get("/billing")
def alias_get_billing(skip: int = 0, limit: int = 100, db: Session = Depends(get_db)):
    return get_billing(skip=skip, limit=limit, db=db)

@app.post("/billing")
def alias_create_billing(payload: dict, db: Session = Depends(get_db)):
    return create_billing(payload=payload, db=db)

# ── DOCTORS endpoints ──────────────────────────────────────────────
@app.get("/api/v1/doctors")
def get_doctors(skip: int = 0, limit: int = 100, db: Session = Depends(get_db)):
    items = db.query(Doctor).offset(skip).limit(limit).all()
    return {"doctors": [{"name": str(i.name) if hasattr(i, "name") else None, "specialization": str(i.specialization) if hasattr(i, "specialization") else None, "department": str(i.department) if hasattr(i, "department") else None, "contact": str(i.contact) if hasattr(i, "contact") else None, "status": str(i.status) if hasattr(i, "status") else None, "id": str(i.id) if hasattr(i, "id") else None, "created_at": str(i.created_at) if hasattr(i, "created_at") else None} for i in items],
            "total": db.query(Doctor).count()}

@app.get("/api/v1/doctors/{item_id}")
def get_doctor(item_id: int, db: Session = Depends(get_db)):
    item = db.query(Doctor).filter(Doctor.id == item_id).first()
    if not item:
        raise HTTPException(status_code=404, detail="Doctor not found")
    return {"name": str(i.name) if hasattr(i, "name") else None, "specialization": str(i.specialization) if hasattr(i, "specialization") else None, "department": str(i.department) if hasattr(i, "department") else None, "contact": str(i.contact) if hasattr(i, "contact") else None, "status": str(i.status) if hasattr(i, "status") else None, "id": str(i.id) if hasattr(i, "id") else None, "created_at": str(i.created_at) if hasattr(i, "created_at") else None}

@app.post("/api/v1/doctors")
def create_doctor(payload: dict, db: Session = Depends(get_db)):
    item = Doctor(
        name=payload.get("name", "")
        specialization=payload.get("specialization", "")
        department=payload.get("department", "")
        contact=payload.get("contact", "")
        status=payload.get("status", 'active')
    )
    db.add(item); db.commit(); db.refresh(item)
    return {"name": str(i.name) if hasattr(i, "name") else None, "specialization": str(i.specialization) if hasattr(i, "specialization") else None, "department": str(i.department) if hasattr(i, "department") else None, "contact": str(i.contact) if hasattr(i, "contact") else None, "status": str(i.status) if hasattr(i, "status") else None, "id": str(i.id) if hasattr(i, "id") else None, "created_at": str(i.created_at) if hasattr(i, "created_at") else None}

@app.put("/api/v1/doctors/{item_id}")
def update_doctor(item_id: int, payload: dict, db: Session = Depends(get_db)):
    item = db.query(Doctor).filter(Doctor.id == item_id).first()
    if not item:
        raise HTTPException(status_code=404, detail="Doctor not found")
    for key, val in payload.items():
        if hasattr(item, key):
            setattr(item, key, val)
    db.commit(); db.refresh(item)
    return {"name": str(i.name) if hasattr(i, "name") else None, "specialization": str(i.specialization) if hasattr(i, "specialization") else None, "department": str(i.department) if hasattr(i, "department") else None, "contact": str(i.contact) if hasattr(i, "contact") else None, "status": str(i.status) if hasattr(i, "status") else None, "id": str(i.id) if hasattr(i, "id") else None, "created_at": str(i.created_at) if hasattr(i, "created_at") else None}

@app.delete("/api/v1/doctors/{item_id}")
def delete_doctor(item_id: int, db: Session = Depends(get_db)):
    item = db.query(Doctor).filter(Doctor.id == item_id).first()
    if not item:
        raise HTTPException(status_code=404, detail="Doctor not found")
    db.delete(item); db.commit()
    return {"deleted": item_id}

# Short alias routes for /doctors
@app.get("/doctors")
def alias_get_doctors(skip: int = 0, limit: int = 100, db: Session = Depends(get_db)):
    return get_doctors(skip=skip, limit=limit, db=db)

@app.post("/doctors")
def alias_create_doctors(payload: dict, db: Session = Depends(get_db)):
    return create_doctor(payload=payload, db=db)

# ── BOOKS endpoints ──────────────────────────────────────────────
@app.get("/api/v1/books")
def get_books(skip: int = 0, limit: int = 100, db: Session = Depends(get_db)):
    items = db.query(Book).offset(skip).limit(limit).all()
    return {"books": [{"title": str(i.title) if hasattr(i, "title") else None, "author": str(i.author) if hasattr(i, "author") else None, "isbn": str(i.isbn) if hasattr(i, "isbn") else None, "genre": str(i.genre) if hasattr(i, "genre") else None, "status": str(i.status) if hasattr(i, "status") else None, "id": str(i.id) if hasattr(i, "id") else None, "created_at": str(i.created_at) if hasattr(i, "created_at") else None} for i in items],
            "total": db.query(Book).count()}

@app.get("/api/v1/books/{item_id}")
def get_book(item_id: int, db: Session = Depends(get_db)):
    item = db.query(Book).filter(Book.id == item_id).first()
    if not item:
        raise HTTPException(status_code=404, detail="Book not found")
    return {"title": str(i.title) if hasattr(i, "title") else None, "author": str(i.author) if hasattr(i, "author") else None, "isbn": str(i.isbn) if hasattr(i, "isbn") else None, "genre": str(i.genre) if hasattr(i, "genre") else None, "status": str(i.status) if hasattr(i, "status") else None, "id": str(i.id) if hasattr(i, "id") else None, "created_at": str(i.created_at) if hasattr(i, "created_at") else None}

@app.post("/api/v1/books")
def create_book(payload: dict, db: Session = Depends(get_db)):
    item = Book(
        title=payload.get("title", "")
        author=payload.get("author", "")
        isbn=payload.get("isbn", "")
        genre=payload.get("genre", "")
        status=payload.get("status", 'available')
    )
    db.add(item); db.commit(); db.refresh(item)
    return {"title": str(i.title) if hasattr(i, "title") else None, "author": str(i.author) if hasattr(i, "author") else None, "isbn": str(i.isbn) if hasattr(i, "isbn") else None, "genre": str(i.genre) if hasattr(i, "genre") else None, "status": str(i.status) if hasattr(i, "status") else None, "id": str(i.id) if hasattr(i, "id") else None, "created_at": str(i.created_at) if hasattr(i, "created_at") else None}

@app.put("/api/v1/books/{item_id}")
def update_book(item_id: int, payload: dict, db: Session = Depends(get_db)):
    item = db.query(Book).filter(Book.id == item_id).first()
    if not item:
        raise HTTPException(status_code=404, detail="Book not found")
    for key, val in payload.items():
        if hasattr(item, key):
            setattr(item, key, val)
    db.commit(); db.refresh(item)
    return {"title": str(i.title) if hasattr(i, "title") else None, "author": str(i.author) if hasattr(i, "author") else None, "isbn": str(i.isbn) if hasattr(i, "isbn") else None, "genre": str(i.genre) if hasattr(i, "genre") else None, "status": str(i.status) if hasattr(i, "status") else None, "id": str(i.id) if hasattr(i, "id") else None, "created_at": str(i.created_at) if hasattr(i, "created_at") else None}

@app.delete("/api/v1/books/{item_id}")
def delete_book(item_id: int, db: Session = Depends(get_db)):
    item = db.query(Book).filter(Book.id == item_id).first()
    if not item:
        raise HTTPException(status_code=404, detail="Book not found")
    db.delete(item); db.commit()
    return {"deleted": item_id}

# Short alias routes for /books
@app.get("/books")
def alias_get_books(skip: int = 0, limit: int = 100, db: Session = Depends(get_db)):
    return get_books(skip=skip, limit=limit, db=db)

@app.post("/books")
def alias_create_books(payload: dict, db: Session = Depends(get_db)):
    return create_book(payload=payload, db=db)

@app.get("/api/v1/stats")
def get_stats(db: Session = Depends(get_db)):
    return {
        "appointments": db.query(Appointment).count(),
    "patients": db.query(Patient).count(),
    "billing": db.query(Billing).count(),
    "doctors": db.query(Doctor).count(),
    "books": db.query(Book).count(),
        "status": "healthy"
    }


if __name__ == "__main__":
    import uvicorn
    port = int(os.getenv("PORT", 8000))
    uvicorn.run("main:app", host="0.0.0.0", port=port, reload=False)
