# models.py — Generated by VIA
from sqlalchemy import Column, Integer, String, Float, DateTime
from sqlalchemy.sql import func
from database import Base

class Appointment(Base):
    __tablename__ = "build_a_hospital_management_system_with__appointments"
    id         = Column(Integer, primary_key=True, index=True)
    doctor_name = Column(String, nullable=True)
    department = Column(String, nullable=True)
    patient_name = Column(String, nullable=True)
    appointment_date = Column(String, nullable=True)
    status = Column(String, default='scheduled')
    created_at = Column(DateTime(timezone=True), server_default=func.now())

class Patient(Base):
    __tablename__ = "build_a_hospital_management_system_with__patients"
    id         = Column(Integer, primary_key=True, index=True)
    name = Column(String, nullable=True)
    age = Column(Integer, nullable=True)
    blood_group = Column(String, nullable=True)
    contact = Column(String, nullable=True)
    diagnosis = Column(String, nullable=True)
    status = Column(String, default='active')
    created_at = Column(DateTime(timezone=True), server_default=func.now())

class Billing(Base):
    __tablename__ = "build_a_hospital_management_system_with__billing"
    id         = Column(Integer, primary_key=True, index=True)
    patient_name = Column(String, nullable=True)
    amount = Column(Float, default=0.0)
    status = Column(String, default='pending')
    description = Column(String, nullable=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now())

class Doctor(Base):
    __tablename__ = "build_a_hospital_management_system_with__doctors"
    id         = Column(Integer, primary_key=True, index=True)
    name = Column(String, nullable=True)
    specialization = Column(String, nullable=True)
    department = Column(String, nullable=True)
    contact = Column(String, nullable=True)
    status = Column(String, default='active')
    created_at = Column(DateTime(timezone=True), server_default=func.now())

class Book(Base):
    __tablename__ = "build_a_hospital_management_system_with__books"
    id         = Column(Integer, primary_key=True, index=True)
    title = Column(String, nullable=True)
    author = Column(String, nullable=True)
    isbn = Column(String, nullable=True)
    genre = Column(String, nullable=True)
    status = Column(String, default='available')
    created_at = Column(DateTime(timezone=True), server_default=func.now())
